## Exercise 1.01: Image and Speech Recognition Demo

This exercise introduces students to the practical application of deep learning by:

- Using a pre-trained model (ResNet50) for image classification
- Converting text output into speech using the Google Text-to-Speech (gTTS) API
- Demonstrating how deep learning models can be integrated into real-world applications with minimal code


In [1]:
from tensorflow.keras.applications.resnet50 import (
    ResNet50,
    preprocess_input,
    decode_predictions,
)
from tensorflow.keras.preprocessing import image
import numpy as np

In [ ]:
model = ResNet50(weights="imagenet")

 46743552/102967424 ━━━━━━━━━━━━━━━━━━━━ 25s 0us/step

In [ ]:
img_path = "house.webp"  # change this to any local image file

In [9]:
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [ ]:
# Predict the image class
predictions = model.predict(x)

# Decode the top-3 predictions
decoded_predictions = decode_predictions(predictions, top=3)[0]

print("Top Predictions:")
for i, (imagenet_id, label, score) in enumerate(decoded_predictions):
    print(f"{i+1}: {label} ({score:.2f})")

# Get the top predicted label
top_label = decoded_predictions[0][1]

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
35363/35363 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Top Predictions:
1: mosque (0.11)
2: cinema (0.10)
3: recreational_vehicle (0.09)


In [ ]:
from gtts import gTTS

# Create a text description
text = f"This image looks like a {top_label}."

# Convert text to speech
tts = gTTS(text)
tts.save("prediction.mp3")

print("Speech saved as prediction.mp3 — play it to hear the result!")

Speech saved as prediction.mp3 — play it to hear the result!


In [ ]:
from tensorflow.keras.applications.resnet50 import (
    ResNet50,
    preprocess_input,
    decode_predictions,
)
from tensorflow.keras.preprocessing import image
import numpy as np
from gtts import gTTS

# Load model
model = ResNet50(weights="imagenet")

# Load and preprocess image
img = image.load_img(img_path, target_size=(224, 224))
x = np.expand_dims(image.img_to_array(img), axis=0)
x = preprocess_input(x)

# Predict and decode
pred = model.predict(x)
label = decode_predictions(pred, top=1)[0][0][1]

# Convert to speech
tts = gTTS(f"This image looks like a {label}.")
tts.save("result.mp3")
print(f"Prediction: {label} (speech saved as result.mp3)")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
Prediction: mosque (speech saved as result.mp3)


## Exercise 1.02: Implementing a Mathematical Equation

This exercise aims to familiarize students with TensorFlow syntax and operations by:

- Defining and using variables and constants
- Implementing a simple mathematical function in TensorFlow
- Executing and printing results within a Jupyter Notebook environment


In [15]:
import tensorflow as tf

In [ ]:
# Step 1: Define constants
a = tf.constant(2.0)
b = tf.constant(3.0)
c = tf.constant(1.0)

# Step 2: Define a variable
x = tf.Variable(5.0)

# Step 3: Define the mathematical equation y = a*x^2 + b*x + c
y = a * tf.pow(x, 2) + b * x + c

# Step 4: Print the result
print("Value of y:", y.numpy())

Value of y: 66.0


In [17]:
for val in [0, 2, 4, 6]:
    x = tf.constant(val, dtype=tf.float32)
    y = a * tf.pow(x, 2) + b * x + c
    print(f"x = {val}, y = {y.numpy()}")

x = 0, y = 1.0
x = 2, y = 15.0
x = 4, y = 45.0
x = 6, y = 91.0


## Exercise 1.03: Matrix Multiplication Using TensorFlow

This exercise reinforces understanding of linear algebra in deep learning by:

- Performing matrix multiplication using tf.matmul()
- Observing how the order of multiplication affects results
- Practicing TensorFlow operations with multi-dimensional tensors


In [ ]:
# Step 1: Define two matrices (2x3 and 3x2)
A = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

B = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.float32)

# Step 2: Perform matrix multiplication A * B
result1 = tf.matmul(A, B)

# Step 3: Perform multiplication in reverse order B * A
result2 = tf.matmul(B, A)

# Step 4: Print results
print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())

print("\nA x B =\n", result1.numpy())
print("\nB x A =\n", result2.numpy())

Matrix A:
 [[1. 2. 3.]
 [4. 5. 6.]]
Matrix B:
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]

A x B =
 [[ 58.  64.]
 [139. 154.]]

B x A =
 [[ 39.  54.  69.]
 [ 49.  68.  87.]
 [ 59.  82. 105.]]


## Exercise 1.04: Reshaping Matrices Using the Reshape Function

This exercise teaches students how to manipulate tensor shapes using:

- The tf.reshape() function to change tensor dimensions
- Understanding how reshaping affects tensor rank and structure
- Applying reshaping to prepare data for neural network input


In [ ]:
# Step 1: Create a 2x3 matrix (rank 2 tensor)
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)

print("Original Tensor:")
print(tensor.numpy())
print("Shape:", tensor.shape)

# Step 2: Reshape into a 3x2 matrix
reshaped_3x2 = tf.reshape(tensor, (3, 2))
print("\nReshaped Tensor (3x2):")
print(reshaped_3x2.numpy())
print("Shape:", reshaped_3x2.shape)

# Step 3: Reshape into a 1D vector (flatten)
flattened = tf.reshape(tensor, (-1,))
print("\nFlattened Tensor (1D):")
print(flattened.numpy())
print("Shape:", flattened.shape)

# Step 4: Reshape into a 3D tensor (1, 2, 3)
reshaped_3d = tf.reshape(tensor, (1, 2, 3))
print("\nReshaped Tensor (1x2x3):")
print(reshaped_3d.numpy())
print("Shape:", reshaped_3d.shape)

Original Tensor:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Reshaped Tensor (3x2):
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)

Flattened Tensor (1D):
[1 2 3 4 5 6]
Shape: (6,)

Reshaped Tensor (1x2x3):
[[[1 2 3]
  [4 5 6]]]
Shape: (1, 2, 3)


## Exercise 1.05: Implementing the Argmax Function

This exercise helps students understand and use the argmax function for:

- Finding the index of the maximum value along a specified axis
- Applying argmax in both row-wise and column-wise contexts
- Preparing for classification tasks in later chapters


In [ ]:
# Step 1: Create a sample 2D tensor (matrix)
tensor = tf.constant([[10, 25, 5], [40, 15, 30], [22, 28, 12]], dtype=tf.float32)

print("Tensor:")
print(tensor.numpy())

# Step 2: Apply argmax row-wise (axis = 1)
# Finds index of max value in each row
row_wise_max = tf.argmax(tensor, axis=1)
print("\nRow-wise Argmax (axis=1):")
print(row_wise_max.numpy())

# Step 3: Apply argmax column-wise (axis = 0)
# Finds index of max value in each column
column_wise_max = tf.argmax(tensor, axis=0)
print("\nColumn-wise Argmax (axis=0):")
print(column_wise_max.numpy())

Tensor:
[[10. 25.  5.]
 [40. 15. 30.]
 [22. 28. 12.]]

Row-wise Argmax (axis=1):
[1 0 1]

Column-wise Argmax (axis=0):
[1 2 1]


## Exercise 1.06: Using an Optimizer for Simple Linear Regression

This exercise introduces the concept of optimization in training models by:

- Defining a linear regression model and a loss function
- Using the Adam optimizer to minimize loss and update parameters
- Observing how model parameters evolve during training to fit the data


In [ ]:
# Step 1: Create synthetic training data
# y = 3x + 2 (true relationship)
X = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
Y = 3 * X + 2

# Step 2: Initialize model parameters (trainable)
w = tf.Variable(0.5)
b = tf.Variable(0.0)


# Step 3: Define the linear model
def model(x):
    return w * x + b


# Step 4: Define the loss function (Mean Squared Error)
def loss_fn(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))


# Step 5: Choose the optimizer (Adam)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)

# Step 6: Training loop
for epoch in range(100):
    with tf.GradientTape() as tape:
        y_pred = model(X)
        loss = loss_fn(Y, y_pred)

    # Compute gradients
    gradients = tape.gradient(loss, [w, b])

    # Update parameters
    optimizer.apply_gradients(zip(gradients, [w, b]))

    # Print progress every 10 epochs
    if epoch % 10 == 0:
        print(
            f"Epoch {epoch:03d}: Loss = {loss.numpy():.4f}, w = {w.numpy():.4f}, b = {b.numpy():.4f}"
        )

Epoch 000: Loss = 102.7500, w = 0.6000, b = 0.1000
Epoch 010: Loss = 35.7158, w = 1.5743, b = 1.0741
Epoch 020: Loss = 5.6016, w = 2.4049, b = 1.9025
Epoch 030: Loss = 0.0297, w = 2.9406, b = 2.4312
Epoch 040: Loss = 0.9395, w = 3.1233, b = 2.6008
Epoch 050: Loss = 0.5886, w = 3.0628, b = 2.5229
Epoch 060: Loss = 0.0637, w = 2.9388, b = 2.3799
Epoch 070: Loss = 0.0388, w = 2.8703, b = 2.2922
Epoch 080: Loss = 0.0454, w = 2.8737, b = 2.2764
Epoch 090: Loss = 0.0189, w = 2.9059, b = 2.2893


## Activity 1.01: Solving a Quadratic Equation Using an Optimizer

This activity applies optimization techniques to solve mathematical problems by:

- Formulating a quadratic equation as a loss function
- Using an optimizer to find the root of the equation
- Reinforcing the concept that optimizers can be used beyond traditional model training


In [ ]:
# Step 1: Define constants for the quadratic equation ax² + bx + c = 0
a = tf.constant(1.0)
b = tf.constant(-3.0)
c = tf.constant(2.0)

# Step 2: Initialize a variable x (our guess for the root)
x = tf.Variable(0.0)


# Step 3: Define the quadratic function
def f(x):
    return a * tf.pow(x, 2) + b * x + c


# Step 4: Define the loss function as the square of f(x)
def loss_fn():
    return tf.square(f(x))


# Step 5: Choose an optimizer (Adam)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)

# Step 6: Optimization loop
for step in range(100):
    with tf.GradientTape() as tape:
        loss = loss_fn()

    # Compute gradients
    gradients = tape.gradient(loss, [x])

    # Apply gradients
    optimizer.apply_gradients(zip(gradients, [x]))

    if step % 10 == 0:
        print(f"Step {step:03d}: x = {x.numpy():.4f}, f(x) = {f(x).numpy():.4f}")

print("\nEstimated Root:", x.numpy())

Step 000: x = 0.1000, f(x) = 1.7100
Step 010: x = 0.9094, f(x) = 0.0988
Step 020: x = 1.2515, f(x) = -0.1882
Step 030: x = 1.3519, f(x) = -0.2281
Step 040: x = 1.3624, f(x) = -0.2311
Step 050: x = 1.3358, f(x) = -0.2230
Step 060: x = 1.2868, f(x) = -0.2045
Step 070: x = 1.2186, f(x) = -0.1708
Step 080: x = 1.1358, f(x) = -0.1174
Step 090: x = 1.0531, f(x) = -0.0503

Estimated Root: 0.9994814
